import React from "react";

interface ExportFooterProps {
  pageNumber: number;
  totalPages: number;
}

const ExportFooter: React.FC<ExportFooterProps> = ({
  pageNumber,
  totalPages,
}) => {
  return (
    <div className="export-footer">
      <span className="export-footer-generated">
        Generated by Pixinerary — Vision Trip Planner AI
      </span>
      <span className="export-footer-page">
        {pageNumber} / {totalPages}
      </span>
    </div>
  );
};

export default ExportFooter;
